package; 

class MainMenuArtsList 
{ 
	public static var data:Map<String,Array<String>> = [ 
		"xeno-2" => ["you-cant-run"],
		"xeno-3" => ["triple-trouble"],
		"xeno-4" => ["final-escape"],
		"coldsteel" => ["personel"],
		"coldsteel-serious" => ["personel-serious"],
		"curse" => ["malediction"],
		"curse-happy" => ["extricate-hex"],
		"demogri" => ["insidious"],
		"devoid" => ["hollow", "empty"],
		"educator" => ["expulsion"],
		"furnace" => ["prey"],
		"gameover_sonic" => ["too-far", "last-hope"],
		"griatos" => ["haze", "marauder"],
		"lord_x" => ["cycles", "fate", "hellbent"],
		"lord_x-encore" => ["cycles-encore"],
		"luther" => ["her-world"],
		"melthog" => ["melting", "confronting"],
		"mono" => ["color-blind"],
		"normalcd" => ["found-you"],
		"requital" => ["forestall-desire"],
		"rosy-alt" => ["coulrophobia"],
		"sanic" => ["too-fest"],
		"satanos" => ["perdition", "underworld"],
		"sonichu" => ["shocker", "extreme-zap"],
		"starved" => ["fight-or-flight"],
		"sunky" => ["cool-party"],
		"sunky-mpeg" => ["milk"],
		"xterion-1" => ["substantial"],
		"xterion-2" => ["digitalized"],
		"majin-us" => ["endless-us"],
		"omw" => ["universal-collapse", "planestrider"],
		"hog" => ["hedge"],
		"scorched" => ["manual-blast"],
		"majin" => ["endless", "endeavors"],
		"needlemouse" => ["relax", "round-a-bout"],
		"fatal-error" => ["fatality", "critical-error"],
		"xeno-encore" => ["you-cant-run-encore"],
		"dsk" => ["miasma"],
		"sh-tails" => ["mania"],
		"fleetway" => ["chaos", "running-wild"],
		"fleetway-encore" => ["chaos-encore"],
		"fakerexe" => ["faker"],
		"noname" => ["forever-unnamed"],
		"tailsdoll-plushie" => ["soulless"],
		"lookalike" => ["face-off"],
		"fakerexe-real" => ["black-sun"],
		"tailsdoll" => ["sunshine"],
		"tailsdoll-encore" => ["sunshine-encore"],
		"gameover_tails" => ["too-far"],
		"soultails" => ["triple-trouble"],
		"soulknuckles" => ["triple-trouble"],
		"sunter" => ["her-world-encore"],
		"souleggman" => ["triple-trouble"],
		"shadowmouse" => ["round-a-bout-encore"],
		"exetior" => ["hellstorm", "sharpy-showdown"],
		"sonic" => ["prey"],
		"chotix" => ["long-sky"],
		"fakerexe-encore" => ["faker-encore"],
		"sl4sh" => ["b4cksl4sh"],
		"chaotix" => ["my-horizon", "our-horizon"],
		"chaotixreal" => ["my-horizon", "our-horizon"],
		"wechidna" => ["my-horizon-wechidna"],
		"wechidnareal" => ["my-horizon-wechidna"],
		"gf-alt" => ["goddess"],
		"xeno-slaps" => ["old-ycr-slaps"],
		"xeno-faker" => ["too-slow-encore"],
		"batman" => ["call-of-justice", "gotta-go"],
		"ugly-sonic" => ["ugly"],
		"buff" => ["endeavors"],
		"lemon" => ["soured"],
		"christmas" => ["jingle-hells"],
		"oxxymajin" => ["oxxynless"],
		"bratwurst" => ["life-and-death"],
		"lord_x-red" => ["gotta-go-red-glove"],
		"majin-og" => ["endless-og"],
		"sarah" => ["relax", "round-a-bout"],
		"bratwurst-2" => ["gods-will"],
		"grimeware-fake" => ["envy"]
	]; 
	 
	public static var arts:Array<String> = [
		"xeno-2",
		"xeno-3",
		"xeno-4",
		"coldsteel",
		"coldsteel-serious",
		"curse",
		"curse-happy",
		"demogri",
		"devoid",
		"educator",
		"furnace",
		"gameover_sonic",
		"griatos",
		"lord_x",
		"lord_x-encore",
		"luther",
		"melthog",
		"mono",
		"normalcd",
		"requital",
		"rosy-alt",
		"sanic",
		"satanos",
		"sonichu",
		"starved",
		"sunky",
		"sunky-mpeg",
		"xterion-1",
		"xterion-2",
		"majin-us",
		"omw",
		"hog",
		"scorched",
		"majin",
		"needlemouse",
		"fatal-error",
		"xeno-encore",
		"dsk",
		"sh-tails",
		"fleetway",
		"fleetway-encore",
		"fakerexe",
		"noname",
		"tailsdoll-plushie",
		"lookalike",
		"fakerexe-real",
		"tailsdoll",
		"tailsdoll-encore",
		"gameover_tails",
		"soultails",
		"soulknuckles",
		"sunter",
		"souleggman",
		"shadowmouse",
		"exetior",
		"sonic",
		"chotix",
		"fakerexe-encore",
		"sl4sh",
		"chaotix",
		"chaotixreal",
		"wechidna",
		"wechidnareal",
		"gf-alt",
		"xeno-slaps",
		"xeno-faker",
		"batman",
		"ugly-sonic",
		"buff",
		"lemon",
		"christmas",
		"oxxymajin",
		"bratwurst",
		"lord_x-red",
		"majin-og",
		"sarah",
		"bratwurst-2",
		"grimeware-fake"
	]; 
	
	public static var secretArts:Array<String> = [
		"pendrive",
		"plushie",
		"xendio",
		"inside-jokes",
		"noname-strings",
		"raton-aguja",
		"silly-tiff",
		"gay",
		"crimson",
		"soonc",
		"soink",
		"woman",
		"grimboob",
		"litr",
		"ladytails",
		"maniax",
		"minus",
		"eris",
		"erismad",
		"exieco",
		"harigami",
		"chukls",
		"metal",
		"luis",
		"alpha",
		"cursed-beast",
		"gangsta",
		"2011",
		"snick",
		"demonix",
		"sans",
		"raw",
		"fetucha",
		"forgotten",
		"loaf",
		"mokey",
		"sketch-hog",
		"squidwurst",
		"sunky-mamado",
		"sonk",
		"hedgehog",
		"feet",
		"lois",
		"doobus",
		"coolcat",
		"first-apparition"
	];
	
	public static var songToArt:Map<String,String>=[]; 
	
	public static function init() {
		songToArt.clear(); 
		for(character in data.keys()) { 
			var songs = data.get(character); 
			for(song in songs)songToArt.set(song,character); 
		}
	} 
	
     public static function getSongsByArt(char:String) { 
		if(data.exists(char))return data.get(char);
		return []; 
	} 
}